//! `genai models sync` — refresh `<data_dir>/models.toml` from the Gemini
//! `models.list` API. The synced overlay covers entries the bundled
//! `data.toml` does not yet know about; bundled entries stay canonical
//! because they carry curated fields the API does not return (pricing,
//! capability labels, thinking levels).

use anyhow::{Context, Result, bail};
use serde::Deserialize;
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use super::{ModelEntry, Registry};
use crate::config::{self, Config};

#[derive(Debug, Deserialize)]
struct ApiList {
    #[serde(default)]
    models: Vec<ApiModel>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ApiModel {
    name: String,
    #[serde(default)]
    display_name: Option<String>,
    #[serde(default)]
    input_token_limit: Option<u32>,
    #[serde(default)]
    output_token_limit: Option<u32>,
    #[serde(default)]
    supported_generation_methods: Vec<String>,
}

pub struct SyncOptions {
    pub dry_run: bool,
}

pub async fn run(cfg: &Config, opts: SyncOptions) -> Result<()> {
    let api_key = cfg.require_api_key()?;
    let bundled: Registry =
        toml::from_str(super::BUNDLED).context("parsing bundled models data")?;
    let bundled_ids: BTreeSet<String> = bundled.models.iter().map(|m| m.id.clone()).collect();

    let live = fetch_models(cfg.api_base(), api_key).await?;
    let live_models: BTreeMap<String, &ApiModel> = live
        .models
        .iter()
        .map(|m| (strip_model_prefix(&m.name).to_string(), m))
        .collect();

    // Categorize.
    let new_ids: Vec<&str> = live_models
        .keys()
        .filter(|id| !bundled_ids.contains(*id))
        .map(|s| s.as_str())
        .collect();
    let deprecated_ids: Vec<&str> = bundled_ids
        .iter()
        .filter(|id| !live_models.contains_key(*id))
        .map(|s| s.as_str())
        .collect();

    eprintln!("== models registry sync ==");
    eprintln!("bundled: {}, live: {}", bundled_ids.len(), live_models.len());
    if !new_ids.is_empty() {
        eprintln!();
        eprintln!("API has, bundled does not:");
        for id in &new_ids {
            let m = live_models[*id];
            let name = m.display_name.as_deref().unwrap_or("");
            let ctx = m.input_token_limit.unwrap_or(0);
            eprintln!("  + {id:<40}  {name:<40}  ctx={ctx}");
        }
    }
    if !deprecated_ids.is_empty() {
        eprintln!();
        eprintln!("Bundled but no longer in live list (likely deprecated):");
        for id in &deprecated_ids {
            eprintln!("  - {id}");
        }
    }
    if new_ids.is_empty() && deprecated_ids.is_empty() {
        eprintln!();
        eprintln!("Registry is in sync. Nothing to write.");
        return Ok(());
    }

    let paths = config::paths()?;
    std::fs::create_dir_all(&paths.data_dir)
        .with_context(|| format!("creating {}", paths.data_dir.display()))?;
    let overlay_path = paths.data_dir.join("models.toml");

    if opts.dry_run {
        eprintln!();
        eprintln!("(dry run; would write {})", overlay_path.display());
        return Ok(());
    }

    let body = render_overlay(&new_ids, &live_models);
    write_atomic(&overlay_path, body.as_bytes())?;
    eprintln!();
    eprintln!("wrote {} ({} new entries)", overlay_path.display(), new_ids.len());
    Ok(())
}

async fn fetch_models(base: &str, api_key: &str) -> Result<ApiList> {
    let url = format!("{base}/v1beta/models");
    tracing::debug!(%url, "models.list");
    let client = reqwest::Client::new();
    let resp = client
        .get(&url)
        .header("x-goog-api-key", api_key)
        .send()
        .await
        .context("GET /v1beta/models")?;
    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        bail!("models.list {status}: {body}");
    }
    let parsed: ApiList = resp.json().await.context("parsing models.list response")?;
    Ok(parsed)
}

fn render_overlay(new_ids: &[&str], live: &BTreeMap<String, &ApiModel>) -> String {
    let mut out = String::new();
    out.push_str(
        "# Generated by `genai models sync`. Do not hand-edit.\n\
         # Capability labels are guesses based on the model id; refine the\n\
         # bundled data.toml for entries you care about long-term.\n\n",
    );
    for id in new_ids {
        let m = live[*id];
        let entry = guess_entry(id, m);
        append_entry(&mut out, &entry);
    }
    out
}

fn guess_entry(id: &str, m: &ApiModel) -> ModelEntry {
    let lower = id.to_ascii_lowercase();
    let capabilities = guess_capabilities(&lower, &m.supported_generation_methods);
    ModelEntry {
        id: id.to_string(),
        display_name: m.display_name.clone().unwrap_or_default(),
        family: guess_family(&lower),
        capabilities,
        context_window: m.input_token_limit.unwrap_or(0),
        max_output_tokens: m.output_token_limit.unwrap_or(0),
        input_price_per_1m: 0.0,
        output_price_per_1m: 0.0,
        supports_thinking: lower.contains("pro") || lower.contains("thinking"),
        thinking_levels: Vec::new(),
        status: if lower.contains("preview") || lower.contains("experimental") {
            "preview".to_string()
        } else {
            "stable".to_string()
        },
    }
}

fn guess_family(lower: &str) -> String {
    for fam in ["gemini-3", "gemini-2.5", "gemini-2", "imagen", "lyria"] {
        if lower.starts_with(fam) {
            return fam.to_string();
        }
    }
    String::new()
}

fn guess_capabilities(lower: &str, methods: &[String]) -> Vec<String> {
    if lower.starts_with("imagen") || lower.contains("-image") {
        return vec![super::CAP_IMAGE_OUT.to_string()];
    }
    if lower.contains("tts") {
        return vec![super::CAP_TTS.to_string()];
    }
    if lower.starts_with("lyria") {
        return vec![super::CAP_MUSIC_OUT.to_string()];
    }
    if lower.starts_with("text-embedding") || lower.contains("embedding") {
        return vec![super::CAP_EMBED.to_string()];
    }
    if methods.iter().any(|m| m == "generateContent") {
        return vec![super::CAP_CHAT.to_string()];
    }
    Vec::new()
}

fn append_entry(out: &mut String, e: &ModelEntry) {
    out.push_str("[[models]]\n");
    out.push_str(&format!("id = \"{}\"\n", e.id));
    if !e.display_name.is_empty() {
        out.push_str(&format!("display_name = \"{}\"\n", escape_str(&e.display_name)));
    }
    if !e.family.is_empty() {
        out.push_str(&format!("family = \"{}\"\n", e.family));
    }
    out.push_str("capabilities = [");
    for (i, c) in e.capabilities.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("\"{c}\""));
    }
    out.push_str("]\n");
    if e.context_window != 0 {
        out.push_str(&format!("context_window = {}\n", e.context_window));
    }
    if e.max_output_tokens != 0 {
        out.push_str(&format!("max_output_tokens = {}\n", e.max_output_tokens));
    }
    if e.supports_thinking {
        out.push_str("supports_thinking = true\n");
    }
    if e.status != "stable" {
        out.push_str(&format!("status = \"{}\"\n", e.status));
    }
    out.push('\n');
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn write_atomic(path: &Path, bytes: &[u8]) -> Result<()> {
    let tmp = path.with_extension("toml.tmp");
    std::fs::write(&tmp, bytes).with_context(|| format!("writing {}", tmp.display()))?;
    std::fs::rename(&tmp, path)
        .with_context(|| format!("renaming into place: {}", path.display()))?;
    Ok(())
}

fn strip_model_prefix(s: &str) -> &str {
    s.strip_prefix("models/").unwrap_or(s)
}
